### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by gleporeNARA** [gleporeNARA/GRIT2#3]
_From @gleporeNARA on March 5, 2018 13:54_

Code cleanup is going well, but I'm concerned about the Resource Leak errors:

Warning:(778, 19) java: Resource leak: 'msg' is never closed
Warning:(815, 25) java: Resource leak: 'extractor' is never closed
Warning:(821, 26) java: Resource leak: 'extractor' is never closed
Warning:(829, 22) java: Resource leak: 'extractor' is never closed

We might run into memory errors.

_Copied from original issue: gleporeNARA/NARA-GRIT#31_

**Comment by bwilso1** [comment]
not seeing any more memory leak warnings.  Only warnings left are code style preferences, which I don't quite agree with.
